// <auto-generated />
using System;
using EF_CoreDay5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CoreDay5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_CoreDay5.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Finance"
                        });
                });

            modelBuilder.Entity("EF_CoreDay5.Models.Employee", b =>
                {
                    b.Property<int>("Employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employeeid"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Employeeid");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Employeeid = 1,
                            DepartmentId = 1,
                            Email = "john@example.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            Employeeid = 2,
                            DepartmentId = 1,
                            Email = "jane@example.com",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Employeeid = 3,
                            DepartmentId = 2,
                            Email = "alice@example.com",
                            Name = "Alice Brown"
                        },
                        new
                        {
                            Employeeid = 4,
                            DepartmentId = 2,
                            Email = "bob@example.com",
                            Name = "Bob White"
                        },
                        new
                        {
                            Employeeid = 5,
                            DepartmentId = 3,
                            Email = "charlie@example.com",
                            Name = "Charlie Black"
                        });
                });

            modelBuilder.Entity("EF_CoreDay5.Models.EmployeeProject", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProjects");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            ProjectId = 1,
                            Role = "Lead Developer"
                        },
                        new
                        {
                            EmployeeId = 2,
                            ProjectId = 1,
                            Role = "Backend Developer"
                        },
                        new
                        {
                            EmployeeId = 3,
                            ProjectId = 2,
                            Role = "Project Manager"
                        },
                        new
                        {
                            EmployeeId = 4,
                            ProjectId = 2,
                            Role = "HR Consultant"
                        },
                        new
                        {
                            EmployeeId = 5,
                            ProjectId = 3,
                            Role = "Finance Analyst"
                        },
                        new
                        {
                            EmployeeId = 1,
                            ProjectId = 3,
                            Role = "Technical Advisor"
                        },
                        new
                        {
                            EmployeeId = 2,
                            ProjectId = 2,
                            Role = "Full Stack Developer"
                        },
                        new
                        {
                            EmployeeId = 3,
                            ProjectId = 1,
                            Role = "Business Analyst"
                        },
                        new
                        {
                            EmployeeId = 4,
                            ProjectId = 3,
                            Role = "Data Analyst"
                        },
                        new
                        {
                            EmployeeId = 5,
                            ProjectId = 1,
                            Role = "Software Engineer"
                        });
                });

            modelBuilder.Entity("EF_CoreDay5.Models.Project", b =>
                {
                    b.Property<int>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projectId"));

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("startDate")
                        .HasColumnType("date");

                    b.HasKey("projectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            projectId = 1,
                            projectName = "ERP System",
                            startDate = new DateOnly(2024, 1, 15)
                        },
                        new
                        {
                            projectId = 2,
                            projectName = "HR Management Tool",
                            startDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            projectId = 3,
                            projectName = "Finance Analytics",
                            startDate = new DateOnly(2024, 3, 5)
                        });
                });

            modelBuilder.Entity("EF_CoreDay5.Models.Employee", b =>
                {
                    b.HasOne("EF_CoreDay5.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EF_CoreDay5.Models.EmployeeProject", b =>
                {
                    b.HasOne("EF_CoreDay5.Models.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_CoreDay5.Models.Project", "Project")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EF_CoreDay5.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EF_CoreDay5.Models.Employee", b =>
                {
                    b.Navigation("EmployeeProjects");
                });

            modelBuilder.Entity("EF_CoreDay5.Models.Project", b =>
                {
                    b.Navigation("EmployeeProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
