// <auto-generated />
using System;
using EF_CoreDay4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CoreDay4.Migrations
{
    [DbContext(typeof(AppDbConnect))]
    [Migration("20250312120342_add_Column_IsVIP")]
    partial class add_Column_IsVIP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_CoreDay4.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsVIP")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            IsVIP = false,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane@example.com",
                            IsVIP = false,
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            IsVIP = false,
                            Name = "Alice Brown"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            IsVIP = false,
                            Name = "Bob Johnson"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlie@example.com",
                            IsVIP = false,
                            Name = "Charlie White"
                        });
                });

            modelBuilder.Entity("EF_CoreDay4.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EF_CoreDay4.Models.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 1,
                            Id = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 1,
                            ProductId = 2,
                            Id = 2,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 3,
                            Id = 3,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 4,
                            Id = 4,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 5,
                            Id = 5,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 5,
                            Id = 6,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("EF_CoreDay4.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop",
                            Price = 1200.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "Smartphone",
                            Price = 799.49m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tablet",
                            Price = 499.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            Name = "Headphones",
                            Price = 199.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            Name = "Smartwatch",
                            Price = 299.99m,
                            Stock = 25
                        });
                });

            modelBuilder.Entity("EF_CoreDay4.Models.Order", b =>
                {
                    b.HasOne("EF_CoreDay4.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EF_CoreDay4.Models.OrderProduct", b =>
                {
                    b.HasOne("EF_CoreDay4.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_CoreDay4.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EF_CoreDay4.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EF_CoreDay4.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("EF_CoreDay4.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
